### ISSUE TITLE
false Positive from manifest_whitespace_opening_bracket_before

### ISSUE THREAD

**Issue by cocker-cc** [kuleuven/puppet-lint-manifest_whitespace-check#11]
I am using `puppet-lint-manifest_whitespace-check (0.1.17)`.

I have Puppet-Code indented with two Space-Characters like this:
```
  [
    'a',
    'b',
  ].each |$i| { }
```
And I get:
```
ERROR: there should be a single space before an opening bracket on line 1 (check: manifest_whitespace_opening_bracket_before)
```

I consider this as a false Positive.

**Comment by greatflyingsteve** [comment]
Additional problem: when using auto-fix, this gets "corrected" by appending the opening bracket to the end of the preceding non-empty line, so that: 
```
include my::class

[
  'a',
  'b',
].each |$i| {}
```
gets corrected to:
```
include my::class [
  'a',
  'b',
].each |$i| {}
```
...which is _a bit of a problem,_ particularly given that starting a line with an anonymous Array is actually part of the [Style Guide recommendations for handling multiple resources.](https://puppet.com/docs/puppet/6/style_guide.html#multiple-resources)  It should ALWAYS be okay to start a line with an opening bracket.

**Comment by jovandeginste** [comment]
I believe this is corrected in the master branch

**Comment by jovandeginste** [comment]
(and now in v0.2.1)
